function [ddx, a_next, a_prime_next] = g_dynamic(dx, x, v0, omega, pitch, M, C, K, AeroParameters, coupling, dynamic_inflow, a_prev, a_prime_prev, dt)

    [F_modal, ~, ~, ~, a_next, a_prime_next, ~] = compute_aero_force_dynamic( ...
        x, dx, v0, omega, pitch, ...
        AeroParameters.radius_aero, AeroParameters.twist_aero, ...
        AeroParameters.phi_1flap_aero, AeroParameters.phi_1edge_aero, ...
        coupling, dynamic_inflow, a_prev, a_prime_prev, dt);

    ddx = M \ (F_modal - C * dx - K * x);
end
