function [StructuralParameters, OperationalParameters, AeroParameters] = load_data()

  %% Load key parameters - AERODYNAMICS
    load 'STATE'

    OperationalParameters.v0_values = WindSpeeds;
    OperationalParameters.omega_values = RtSpeeds * 2 * pi / 60;
    OperationalParameters.pitch_values = PitchAngles;

    %% Load structural blade data
    structural_data = importdata("Structural data.txt");

    StructuralParameters.radius = structural_data.data(:,1);
    StructuralParameters.blade_position = structural_data.data(:,2);
    StructuralParameters.mass_distribution = structural_data.data(:, 5);
    StructuralParameters.flap_stiffness_distribution = structural_data.data(:, 6);
    StructuralParameters.edge_stiffness_distribution = structural_data.data(:, 7);
    StructuralParameters.R = StructuralParameters.radius(end);

    %% Damping
    StructuralParameters.damping_flapwise = 0.477465;
    StructuralParameters.damping_edgewise = StructuralParameters.damping_flapwise;

    %% Shape functions

    % Normalized blade position (xi = r/R)
    xi = StructuralParameters.blade_position;
    R = StructuralParameters.R;

    %% Flapwise shape function and its derivatives
    StructuralParameters.phi_1flap = ...
        0.0622  * xi.^2 + ...
        1.7254  * xi.^3 - ...
        3.2452  * xi.^4 + ...
        4.7131  * xi.^5 - ...
        2.2555  * xi.^6;
        
    StructuralParameters.dphi_1flap = (1 / R) * ( ...
          2 * 0.0622   * xi + ...
          3 * 1.7254   * xi.^2 - ...
          4 * 3.2452   * xi.^3 + ...
          5 * 4.7131   * xi.^4 - ...
          6 * 2.2555   * xi.^5 );

    StructuralParameters.ddphi_1flap = (1 / R^2) * ( ...
          2 * 0.0622   + ...
          6 * 1.7254   * xi - ...
        12 * 3.2452   * xi.^2 + ...
        20 * 4.7131   * xi.^3 - ...
        30 * 2.2555   * xi.^4 );

    %% Edgewise shape function and its derivatives
    StructuralParameters.phi_1edge = ...
        0.3627  * xi.^2 + ...
        2.5337  * xi.^3 - ...
        3.5772  * xi.^4 + ...
        2.376   * xi.^5 - ...
        0.6952  * xi.^6;

    StructuralParameters.dphi_1edge = (1 / R) * ( ...
          2 * 0.3627   * xi + ...
          3 * 2.5337   * xi.^2 - ...
          4 * 3.5772   * xi.^3 + ...
          5 * 2.376    * xi.^4 - ...
          6 * 0.6952   * xi.^5 );

    StructuralParameters.ddphi_1edge = (1 / R^2) * ( ...
          2 * 0.3627   + ...
          6 * 2.5337   * xi - ...
        12 * 3.5772   * xi.^2 + ...
        20 * 2.376    * xi.^3 - ...
        30 * 0.6952   * xi.^4 );


    %% Mass & Stiffness
    StructuralParameters.M_1flap = trapz(StructuralParameters.radius, StructuralParameters.mass_distribution.*(StructuralParameters.phi_1flap.^2));
    StructuralParameters.M_1edge = trapz(StructuralParameters.radius, StructuralParameters.mass_distribution.*(StructuralParameters.phi_1edge.^2));
    StructuralParameters.K_1flap = trapz(StructuralParameters.radius, StructuralParameters.flap_stiffness_distribution.*(StructuralParameters.ddphi_1flap.^2));
    StructuralParameters.K_1edge = trapz(StructuralParameters.radius, StructuralParameters.edge_stiffness_distribution.*(StructuralParameters.ddphi_1edge.^2));

    StructuralParameters.M = diag([StructuralParameters.M_1flap, StructuralParameters.M_1edge]);
    StructuralParameters.K = diag([StructuralParameters.K_1flap, StructuralParameters.K_1edge]);
    StructuralParameters.C = diag([2*StructuralParameters.damping_flapwise * sqrt(StructuralParameters.K_1flap*StructuralParameters.M_1flap), ...
            2*StructuralParameters.damping_edgewise * sqrt(StructuralParameters.K_1edge*StructuralParameters.M_1edge)]);

    %% Natural frequencies
    StructuralParameters.omega_1flap = sqrt(StructuralParameters.K_1flap/StructuralParameters.M_1flap);
    StructuralParameters.omega_1edge = sqrt(StructuralParameters.K_1edge/StructuralParameters.M_1edge);

    %% Aerodynamic properties
    blade_data = importdata('Blade/Blade section/Blade section.dat');
    AeroParameters.twist_aero = blade_data.data(:,5);
    AeroParameters.radius_aero = blade_data.data(:,3);
    AeroParameters.blade_position_aero = AeroParameters.radius_aero/StructuralParameters.R;

    AeroParameters.phi_1flap_aero = 0.0622*AeroParameters.blade_position_aero.^2 + 1.7254*AeroParameters.blade_position_aero.^3 - ...
                    3.2452*AeroParameters.blade_position_aero.^4 + 4.7131*AeroParameters.blade_position_aero.^5 - ...
                    2.2555*AeroParameters.blade_position_aero.^6;

    AeroParameters.dphi_1flap_aero = (1 / StructuralParameters.R) * ( ...
          2 * 0.0622   * AeroParameters.blade_position_aero + ...
          3 * 1.7254   * AeroParameters.blade_position_aero.^2 - ...
          4 * 3.2452   * AeroParameters.blade_position_aero.^3 + ...
          5 * 4.7131   * AeroParameters.blade_position_aero.^4 - ...
          6 * 2.2555   * AeroParameters.blade_position_aero.^5 );

    AeroParameters.phi_1edge_aero = 0.3627*AeroParameters.blade_position_aero.^2 + 2.5337*AeroParameters.blade_position_aero.^3 - ...
                    3.5772*AeroParameters.blade_position_aero.^4 + 2.376*AeroParameters.blade_position_aero.^5 - ...
                    0.6952*AeroParameters.blade_position_aero.^6;
    AeroParameters.dphi_1edge_aero = (1 / StructuralParameters.R) * ( ...
              2 * 0.3627   * AeroParameters.blade_position_aero + ...
              3 * 2.5337   * AeroParameters.blade_position_aero.^2 - ...
              4 * 3.5772   * AeroParameters.blade_position_aero.^3 + ...
              5 * 2.376    * AeroParameters.blade_position_aero.^4 - ...
              6 * 0.6952   * AeroParameters.blade_position_aero.^5 );
end
